# Generated by Django 4.1.1 on 2022-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('department', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_info', models.DateField()),
                ('updated_info', models.DateField(auto_now_add=True)),
                ('last_info', models.DateField(auto_now=True)),
            ],
        ),
    ]
